import 'package:flutter/material.dart';

// Main
const PRIMARY_COLOR = Color(0xFF4273B1);
const SECONDARY_COLOR = Color(0xFF081F5C);

// Text Color
const DEFAULT_TEXT_COLOR = Color(0xFF1C1C1E);
const WHITE_TEXT_COLOR = Color(0xFFFFFFFF);
const PLACEHOLDER_COLOR = Color(0XFF8E8E93);

// Grey
const DARK_GREY_COLOR = Color(0xFF888888);
const MIDDLE_GREY_COLOR = Color(0xFFDCDCDD);
const LIGHT_GREY_COLOR = Color(0xFFEFF1F3);
const DISABLED_BUTTON_BACKGROUND_COLOR = Color(0xFFDCDCDC);
const DISABLED_BUTTON_FOREGROUND_COLOR = Color(0xFF999898);

// Background Color
const BARRIER_COLOR = Color(0X661C1C1E);
const EMPTY_COLOR = Color(0X00000000);
const BACKGROUND_COLOR = Color(0xFFFFFFFF);

// Error
const ERROR_COLOR = Color(0xFFFF555F);

// Text Field Color
const INPUT_BORDER_COLOR = Color(0xFFAEAEB2);

// Stroke Color
const STROKE_TEXT_FIELD_COLOR = Color(0XFFAEAEB2);
const SHADOW_COLOR = Colors.black;


// KAKAO LOGIN
const KAKAO_TEXT_COLOR = Color(0xD9000000);
const KAKAO_CONTAINER_COLOR = Color(0xFFFEE500);

// APPLE LOGIN
const APPLE_TEXT_COLOR = Color(0xFFFFFFFF);
const APPLE_CONTAINER_COLOR = Color(0xFF000000);
